#pragma once

#define CL_HPP_TARGET_OPENCL_VERSION 200
#include <CL/opencl.hpp>
#include <cstdint>
#include <cstdio>
#include <vector>

#include "adam.hpp"
#include "engine.hpp"
#include "features.hpp"
#include "shogi.hpp"
#include "play.hpp"



namespace Train
{

/**
 * @struct TrainingData
 * @brief Contains the description on one board state for training.
 */
struct TrainingData
{
	int32_t features_current[40]; // current player features at this game state. 
	int32_t features_other[40];   // Other player features at this game state.
	int32_t num_current;          // Number of current player active features.
	int32_t num_other;            // Number of other player active features.
	int32_t score;                // Score of this state. 
	float game_result;            // 1.0 (current player win), 0.0 (lost), 0.5 (null).
};



/**
 * @brief Exract all active features from a given game state.
 * @param state The state to extract the features from.
 * @param current_player The currently playing player.
 * @param data A reference to the place where to store the features indexes.  
 */
inline void extract_active_features(const Shogi::State &state, Shogi::Player current_player, TrainingData &data)
{
	const int32_t king_sente = state.king_sq(Shogi::Player::SENTE);
	const int32_t king_gote  = state.king_sq(Shogi::Player::GOTE);
	data.num_current = 0;
	data.num_other = 0;

	// Lambda to put the features automatically in the right buffer.
	auto push_feature = [&](int32_t id_sente, int32_t id_gote)
	{
		if (current_player == Shogi::Player::SENTE) {
			data.features_current[data.num_current++] = id_sente;
			data.features_other[data.num_other++] = id_gote;
		} else {
			data.features_current[data.num_current++] = id_gote;
			data.features_other[data.num_other++] = id_sente;
		}
	};

	// Get the board pieces features.
	const Shogi::Piece *board = state.data();
	for (int32_t sq = 0; sq < 81; ++sq) {
		Shogi::Piece p = board[sq];
		if (p.piece() == Shogi::PieceType::UNKNOWN) continue;	
		int32_t f_sente = -1;
		int32_t f_gote = -1;

		// Specific case to get the other player king feature.
		if (!(p.piece() == Shogi::PieceType::K && p.player() == Shogi::Player::SENTE))
			f_sente = NNUE::get_board_feature_index(Shogi::Player::SENTE, king_sente, p, sq);
		if (!(p.piece() == Shogi::PieceType::K && p.player() == Shogi::Player::GOTE))
			f_gote = NNUE::get_board_feature_index(Shogi::Player::GOTE, king_gote, p, sq);

		// Push the features in the buffers.
		if (f_sente != -1 || f_gote != -1) push_feature(f_sente, f_gote);
	
	}

	// Get the hand pieces features for each player.
	for (int32_t player = 0; player < 2; ++player) {
		Shogi::Player owner = static_cast<Shogi::Player>(player);
		const auto &hand = state.hands(owner);
		
		// Get the number of each piece in hand.
		for (int32_t pt = Shogi::PieceType::R; pt <= Shogi::PieceType::P; ++pt) {
			int32_t count = hand[pt];
			if (count <= 0) continue;
			
			// Get the feature id and push it in the buffers.
			Shogi::PieceType p_type = static_cast<Shogi::PieceType>(pt);
			int32_t f_sente = NNUE::get_hand_feature_index(Shogi::Player::SENTE, king_sente, owner, p_type, count);
			int32_t f_gote  = NNUE::get_hand_feature_index(Shogi::Player::GOTE, king_gote, owner, p_type, count);
			push_feature(f_sente, f_gote);
			
		}
	}

}



/**
 * @brief Generate a whole game and dump its history in a binary file.
 * @param network The NNUE to use to play.
 * @param dataset ofstream to the dataset binary file where to store the history.
 * @return The number of examples generated by this function.
 */
inline int32_t generate_selfplay_game(const NNUE::NNUE &network, std::ofstream &dataset)
{
    Shogi::State state = Shogi::State::make_default();
	NNUE::Accumulator acc;
    NNUE::refresh_accumulator(network, acc, state);

	// Prepare the game history.
    struct HistoryEntry 
	{
        TrainingData data;
        Shogi::Player turn;
    };
    std::vector<HistoryEntry> game_history;
    game_history.reserve(256);

	// Generate the game.
    Shogi::Player current_player = Shogi::Player::SENTE;
    int32_t current_turn = 0;
    bool is_draw = false;
    Shogi::Player winner = Engine::OPPONENT[Shogi::Player::SENTE];;
    while (current_turn < 256) {
        
		// Save the current state features.
		game_history.emplace_back();
		HistoryEntry &current_entry = game_history.back(); 
        extract_active_features(state, current_player, current_entry.data); 
		current_entry.turn = current_player;

		// Find the best move to do and save its score.
		// Use high temperature at the beginning for exploration.
        const double temp = (current_turn < 16) ? 30.0 : 0.1;
        int32_t best_move_score = 0;
        const Shogi::Move best_move = Engine::search_move(best_move_score, network, state, acc, 1, current_player, temp);
        current_entry.data.score = best_move_score;

        // Detect end of games.
		if (best_move.piece() == Shogi::PieceType::UNKNOWN) {
            winner = Engine::OPPONENT[current_player];
            break; 
        }

		// Play the move and update the accumulator.
        const bool is_king = best_move.piece() == Shogi::K;
        if (!is_king) NNUE::update_accumulator(network, acc, state, best_move);
        state(best_move);
        if (is_king) NNUE::refresh_accumulator(network, acc, state);

		// Pass to the next player turn.
        current_player = Engine::OPPONENT[current_player];
        ++current_turn;
    }

	// If the game is too long it is a draw.
    if (current_turn >= 256) is_draw = true;

	// Annotate all entries.
    for (auto &entry : game_history) {
        if (is_draw) entry.data.game_result = 0.5f;
        else if (winner == entry.turn) entry.data.game_result = 1.0f;
        else  entry.data.game_result = 0.0f;
    }

	// Write the history.
	dataset.write(
		reinterpret_cast<const char*>(game_history.data()), 
		game_history.size() * sizeof(TrainingData)
	);
	return game_history.size();

}



/**
 * @brief Add games to the dataset and update the header.
 * @param path The path to the dataset.
 * @param network The NNUE to use for generation.
 * @param nb_games The number of games to generate.
 */
inline void add_training_data(const std::string &path, const NNUE::NNUE &network, int32_t nb_games)
{
	// Open the file for binary I/O.
	std::fstream file(path, std::ios::binary | std::ios::in | std::ios::out);
	int32_t total_examples = 0;
	int32_t total_games = 0;

	// If it failed the file do not exist so we create it and reopen it.
	if (!file.is_open()) {
		std::ofstream creator(path, std::ios::binary);
		creator.write(reinterpret_cast<const char*>(&total_examples), sizeof(int32_t));
		creator.write(reinterpret_cast<const char*>(&total_games), sizeof(int32_t));
		creator.close();
		file.open(path, std::ios::binary | std::ios::in | std::ios::out);
		if (!file.is_open()) return;

	// Else it exists and we read the counters.
	} else {
		file.read(reinterpret_cast<char*>(&total_examples), sizeof(int32_t));
		file.read(reinterpret_cast<char*>(&total_games), sizeof(int32_t));
	}

	// Add the new data.
	file.seekp(0, std::ios::end);
	for (int32_t g = 0; g < nb_games; ++g) {
		int32_t added_moves = generate_selfplay_game(network, (std::ofstream&)file);
		total_examples += added_moves;
		printf("\rProgress: Game %d/%d | Total Positions: %d", total_games + g + 1, total_games + nb_games, total_examples);
		fflush(stdout);
	}
	printf("\n");
	total_games += nb_games;

	// Update the counters.
	file.seekp(0, std::ios::beg);
	file.write(reinterpret_cast<const char*>(&total_examples), sizeof(int32_t));
	file.write(reinterpret_cast<const char*>(&total_games), sizeof(int32_t));
	
	file.close();
	std::cout << "Dataset updated: " << total_games << " games, " << total_examples << " examples." << std::endl;
}

/**
 * @brief Load a dataset from a binary file.
 * @param path The path of the dataset.
 * @param dataset The dataset buffer.
 */
inline void load_dataset(const std::string &path, std::vector<TrainingData> &dataset)
{
	std::ifstream file(path, std::ios::binary);
	if (!file.is_open()) {
		std::cerr << "Error: Failed to read the dataset '" << path << "'\n";
		exit(1);
	}
	int32_t total_examples = 0;
	int32_t total_games = 0;
	file.read(reinterpret_cast<char*>(&total_examples), sizeof(int32_t));
	file.read(reinterpret_cast<char*>(&total_games), sizeof(int32_t));
	std::cout << "Loading " << total_examples << " examples from " << total_games << " games.\n";
	dataset.resize(total_examples);
	file.read(reinterpret_cast<char*>(dataset.data()), total_examples * sizeof(TrainingData));
	file.close();
}



/**
 * @class Trainer
 * @brief Used to perform forward and backward pass during training.
 */ 
class Trainer
{
private:
	cl::Context context;
	cl::CommandQueue queue;
	cl::Program program;
	cl::Kernel quantize_kernel;
	cl::Kernel train_kernel;

	cl::Buffer d_batch;
	cl::Buffer d_q_weights;
	cl::Buffer d_loss;
	
	int32_t batch_capacity;
	int32_t total_params;

	int32_t off_in_w, off_in_b;
	int32_t off_fc1_w, off_fc1_b;
	int32_t off_fc2_w, off_fc2_b;
	int32_t off_out_w, off_out_b;

public:
	Trainer(cl::Context ctx, cl::Device device, cl::CommandQueue q, int32_t max_batch_size)
	{
		context = ctx;
		queue = q;
		batch_capacity = max_batch_size;
		total_params = sizeof(NNUE::NNUEFloat) / sizeof(float);

		// Forward/Backward kernel compilation
		std::ifstream file("nnue.cl");
		if (!file.is_open()) {
			std::cerr << "Error: Failed to open 'nnue.cl'\n";
			exit(1);
		}
		std::string source((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
		cl::Program::Sources sources;
		sources.push_back({source.c_str(), source.length()});
		
		program = cl::Program(context, sources);
		if (program.build({device}) != CL_SUCCESS) {
			std::cerr << "Error:\n" << program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(device) << "\n";
			exit(1);
		}
		
		quantize_kernel = cl::Kernel(program, "quantize_weights");
		train_kernel = cl::Kernel(program, "forward_backward");

		d_batch = cl::Buffer(context, CL_MEM_READ_ONLY, sizeof(TrainingData) * batch_capacity);
		d_q_weights = cl::Buffer(context, CL_MEM_READ_WRITE, total_params * sizeof(int32_t));
		d_loss = cl::Buffer(context, CL_MEM_READ_WRITE, sizeof(float));

		off_in_w  = offsetof(NNUE::NNUEFloat, in_weights) / sizeof(float);
		off_in_b  = offsetof(NNUE::NNUEFloat, in_bias) / sizeof(float);
		off_fc1_w = offsetof(NNUE::NNUEFloat, fc1_weights) / sizeof(float);
		off_fc1_b = offsetof(NNUE::NNUEFloat, fc1_bias) / sizeof(float);
		off_fc2_w = offsetof(NNUE::NNUEFloat, fc2_weights) / sizeof(float);
		off_fc2_b = offsetof(NNUE::NNUEFloat, fc2_bias) / sizeof(float);
		off_out_w = offsetof(NNUE::NNUEFloat, output_weights) / sizeof(float);
		off_out_b = offsetof(NNUE::NNUEFloat, output_bias) / sizeof(float);
	}

	float train_batch(Adam &optimizer, const std::vector<TrainingData> &batch, float lambda = 0.5f, float scale = 400.0f)
	{
		int32_t current_batch_size = batch.size();
		if (current_batch_size > batch_capacity) return 0.0f;

		float zero = 0.0f;
		queue.enqueueWriteBuffer(d_loss, CL_TRUE, 0, sizeof(float), &zero);
		
		// Prepare quantization arguments
		int32_t q_arg = 0;
		quantize_kernel.setArg(q_arg++, optimizer.get_weights());
		quantize_kernel.setArg(q_arg++, d_q_weights);
		quantize_kernel.setArg(q_arg++, off_in_w);
		quantize_kernel.setArg(q_arg++, off_in_b);
		quantize_kernel.setArg(q_arg++, off_fc1_w);
		quantize_kernel.setArg(q_arg++, off_fc1_b);
		quantize_kernel.setArg(q_arg++, off_fc2_w);
		quantize_kernel.setArg(q_arg++, off_fc2_b);
		quantize_kernel.setArg(q_arg++, off_out_w);
		quantize_kernel.setArg(q_arg++, off_out_b);
		quantize_kernel.setArg(q_arg++, total_params);

		// Launch quantization kernel across all parameters (runs once per batch)
		cl::NDRange global_q_size(total_params);
		queue.enqueueNDRangeKernel(quantize_kernel, cl::NullRange, global_q_size, cl::NullRange);

		// Prepare forward/backward arguments
		queue.enqueueWriteBuffer(d_batch, CL_TRUE, 0, current_batch_size * sizeof(TrainingData), batch.data());

		int32_t arg = 0;
		train_kernel.setArg(arg++, d_batch);
		train_kernel.setArg(arg++, optimizer.get_weights());
		train_kernel.setArg(arg++, d_q_weights);
		train_kernel.setArg(arg++, optimizer.get_gradients());
		
		train_kernel.setArg(arg++, off_in_w);
		train_kernel.setArg(arg++, off_in_b);
		train_kernel.setArg(arg++, off_fc1_w);
		train_kernel.setArg(arg++, off_fc1_b);
		train_kernel.setArg(arg++, off_fc2_w);
		train_kernel.setArg(arg++, off_fc2_b);
		train_kernel.setArg(arg++, off_out_w);
		train_kernel.setArg(arg++, off_out_b);

		train_kernel.setArg(arg++, current_batch_size);
		train_kernel.setArg(arg++, lambda);
		train_kernel.setArg(arg++, scale);
		train_kernel.setArg(arg++, d_loss);

		// Launch training kernel across the batch size
		cl::NDRange global_work_size(current_batch_size);
		queue.enqueueNDRangeKernel(train_kernel, cl::NullRange, global_work_size, cl::NullRange);
		
		// Synchronize
		queue.finish();

		// Return the loss.
		float total_loss = 0.0f;
		queue.enqueueReadBuffer(d_loss, CL_TRUE, 0, sizeof(float), &total_loss);
		return total_loss / (float)current_batch_size;

	}
};

};
